# Site settings
title: Diseño de Sistemas
email: dds-jv-cursada@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"
  Conocé más sobre ésta temática
baseurl: ""
url: "https://dds-jv.github.io"

# Tooltip settings
tooltip-enabled: true
tooltip-label: "Buscamos a Arshak Karhanyan"
tooltip-link: "http://siga.frba.utn.edu.ar/up/docs/PERSONA%20PERDIDA.jpeg"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
